DROP TABLE IF EXISTS ITENS CASCADE;
DROP TABLE IF EXISTS LOCACOES CASCADE;
DROP TABLE IF EXISTS FILMES CASCADE;
DROP TABLE IF EXISTS CATEGORIAS CASCADE;
DROP TABLE IF EXISTS CLIENTES CASCADE;

CREATE TABLE CLIENTES (
  CLI_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLI_NOME VARCHAR(50) NOT NULL,
  CLI_TELEFONE VARCHAR(25),
  CLI_DATA_CAD TIMESTAMP DEFAULT NOW(),
  CLI_SALDO NUMERIC(10,2) CHECK (CLI_SALDO >= 0)
);

CREATE TABLE CATEGORIAS (
  CAT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CAT_NOME VARCHAR(150) NOT NULL,
  CAT_DATA_CAD TIMESTAMP DEFAULT NOW()
);

CREATE TABLE FILMES (
  FIL_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FIL_NOME VARCHAR(150) NOT NULL,
  FIL_CAT_ID INTEGER,
  FIL_DATA_CAD TIMESTAMP DEFAULT NOW(),
  CONSTRAINT FK_FILMES_CATEGORIAS
    FOREIGN KEY (FIL_CAT_ID)
    REFERENCES CATEGORIAS(CAT_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE LOCACOES (
  LOC_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LOC_CLI_ID INTEGER,
  LOC_DATA_CAD TIMESTAMP DEFAULT NOW(),
  CONSTRAINT FK_LOCACOES_CLIENTES
    FOREIGN KEY (LOC_CLI_ID)
    REFERENCES CLIENTES(CLI_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE ITENS (
  ITN_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ITN_LOC_ID INTEGER,
  ITN_FIL_ID INTEGER,
  ITN_VALOR_LOC NUMERIC(10,2) CHECK (ITN_VALOR_LOC >= 0),
  CONSTRAINT FK_ITENS_LOCACOES
    FOREIGN KEY (ITN_LOC_ID)
    REFERENCES LOCACOES(LOC_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_ITENS_FILMES
    FOREIGN KEY (ITN_FIL_ID)
    REFERENCES FILMES(FIL_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

INSERT INTO CLIENTES
(CLI_NOME, CLI_TELEFONE, CLI_DATA_CAD, CLI_SALDO)
VALUES
('JOAO BATISTA', '(62) 99999-9999', NOW(), 100.00),
('JOSE CARLOS', '(62) 98888-8888', NOW(), 150.00),
('MANOEL CARLOS', '(62) 97777-7777', NOW(), 90.00),
('PEDRO PAULO', '(62) 96666-6666', NOW(), 200.00),
('JOAQUIM NABUCO', '(62) 95555-5555', NOW(), 250.00);

INSERT INTO CATEGORIAS
(CAT_NOME, CAT_DATA_CAD)
VALUES
('ACAO', NOW()),
('ANIMACAO', NOW()),
('COMEDIA', NOW()),
('DOCUMENTARIO', NOW()),
('DRAMA', NOW()),
('FANTASIA', NOW()),
('FAROESTE/WESTERN', NOW()),
('FICCAO CIENTIFICA (Sci-Fi)', NOW()),
('ROMANCE', NOW()),
('SUSPENSE/THRILLER', NOW()),
('TERROR/HORROR', NOW());

INSERT INTO FILMES
(FIL_NOME, FIL_CAT_ID, FIL_DATA_CAD)
VALUES
('MATRIX', 1, NOW()),
('MATRIX RELOADED', 1, NOW()),
('MATRIX REVOLUTIONS', 1, NOW()),
('O REI LEAO', 2, NOW()),
('O SENHOR DOS ANEIS - A SOCIEDADE DO ANEL', 6, NOW()),
('TOY STORY', 2, NOW()),
('AUTO DA COMPADECIDA', 3, NOW()),
('O GRANDE DITADOR', 3, NOW()),
('COSMOS', 4, NOW()),
('PLANETA TERRA', 4, NOW()),
('CENTRAL DO BRASIL', 5, NOW()),
('O PODEROSO CHEFAO', 5, NOW()),
('HARRY POTTER E A PEDRA FILOSOFAL', 6, NOW()),
('TRES HOMENS EM CONFLITO', 7, NOW()),
('OS IMPERDOAVEIS', 7, NOW()),
('INTERESTELAR', 8, NOW()),
('BLADE RUNNER', 8, NOW()),
('TITANIC', 9, NOW()),
('DIARIO DE UMA PAIXAO', 9, NOW()),
('ILHA DO MEDO', 10, NOW()),
('O SILENCIO DOS INOCENTES', 10, NOW()),
('O ILUMINADO', 11, NOW()),
('PSICOSE', 11, NOW());

INSERT INTO LOCACOES
(LOC_CLI_ID, LOC_DATA_CAD)
VALUES
(1, NOW()),
(2, NOW()),
(3, NOW()),
(4, NOW()),
(5, NOW());

INSERT INTO ITENS
(ITN_LOC_ID, ITN_FIL_ID, ITN_VALOR_LOC)
VALUES
(1, 1, 10.50),
(1, 2, 10.50),
(1, 3, 12.50),
(1, 5, 15.00),
(2, 4, 8.00),
(2, 6, 8.00),
(3, 7, 9.50),
(3, 11, 11.00),
(4, 16, 14.00),
(4, 17, 14.00),
(5, 20, 12.00),
(5, 22, 13.50);
